version: "2"

linters:
  default: standard
  enable:
    - copyloopvar
    - errname
    - errorlint
    - gofumpt
    - govet
    - misspell
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace

formatters:
  enable:
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
